version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packes...
      - npm install
    build:
      commands:
        - echo Create build...
        - npm run build
    post_build:
      commands:
        - echo Removing unnecessay files....
        - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'