version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packes...
      - npm install
    build:
      commands:
        - echo build production
        - npm run build
artifacts:
  base-directory: '.'
  files:
    - '**/*'